version: '3'
services:
  db:
    build: './db'
    restart: always
    image: db_image
    networks:
      - back-db-tier
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=${DB_SQL_USER:-db}
      - MYSQL_PASSWORD=${DB_SQL_PASSWORD:-dbpassword}
      - MYSQL_DATABASE=${DB_SQL_DATABASE:-dashboard}
      - MYSQL_ROOT_PASSWORD=${DB_SQL_ROOT_PASSWORD:-root}

  front:
    build: './client'
    restart: always
    image: front_image
    networks:
      - front-back-tier
    ports:
      - '8080:8080'
    environment:
      - PORT=8080

  server:
    build: './server'
    restart: always
    image: server_image
    networks:
      - back-db-tier
      - front-back-tier
    ports:
      - '5000:80'
    environment:
      - HOST_PORT=80
      - MYSQL_USER=${DB_SQL_USER:-db}
      - MYSQL_PASSWORD=${DB_SQL_PASSWORD:-dbpassword}
      - MYSQL_DATABASE=${DB_SQL_DATABASE:-dashboard}
      - MYSQL_HOST=${DB_SQL_HOST:-db}

networks:
  back-db-tier:
  front-back-tier:

